name: Package tests
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - python-version: '3.10'
            globus-sdk: 'globus-sdk==3.65.0'
          - python-version: '3.13'
            globus-sdk: 'globus-sdk'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - run: python -m pip install ./python build "${{ matrix.globus-sdk }}"
      - run: python -m unittest discover -s python/tests -v
      - run: python -m build python
      - run: |
          python -m pip install --force-reinstall --no-deps python/dist/*.whl
          cd "$RUNNER_TEMP"
          nersc-tokens list-services
          python -m nersc_tokens --help
